### ISSUE TITLE
Abstract DriveTrainSubsystem logic away in TeleopDriveCommand

### ISSUE THREAD

**Issue by vchen04** [BadRobots1014/BadRobot2022#3]
In `TeleopDriveCommand`, the following lines exist in the `execute` method:

https://github.com/BadRobots1014/BadRobot2022/blob/6ab6deebb9e31c4f6d5a65280fab43226a4b1c77/src/main/java/frc/robot/commands/TeleopDriveCommand.java#L142-L148

One of the goals of having these `DriveStrategy` classes is that all logic that deals directly with the `DriveTrainSubsystem`, e.g., setting motor speeds, is handled by the `DriveStrategy` classes and not the context (client code, in this case `TeleopDriveCommand`) that uses them. To do this, we'd execute the methods like `DriveTrainSubsystem::tankDrive` within the `DriveStrategy` classes.

Additionally, this would mean that the `execute` method of `DriveStrategy` wouldn't return `WheelSpeeds`, and would instead be a void method.

https://github.com/BadRobots1014/BadRobot2022/blob/6ab6deebb9e31c4f6d5a65280fab43226a4b1c77/src/main/java/frc/robot/commands/drive/DriveStrategy.java#L20-L28

Ideally, code that handles `WheelSpeeds` objects would be in the `DriveTrainSubsystem` class since the `DriveTrainSubsystem` should be responsible for translating any configuration of wheel speeds into physical actions on the robot. This idea suggests the following data flow:

1. User input (joystick inputs)
2. `TeleopDriveCommand` (interprets joystick inputs and delegates to the appropriate `DriveStrategy`)
3. `DriveStrategy` (interfaces appropriately with the `DriveTrainSubsystem`)
4. `DriveTrainSubsystem` (handles calls from `DriveStrategy`)

**Comment by wxb1ank** [comment]
Sorry; I'll change it back. My reasoning was that the only interaction a drive strategy would have with `DriveTrainSubsystem` is setting wheel speeds, and so it would save a few lines to return a `WheelSpeeds` object that's fed to `DriveTrainSubsystem` in a central place. But, the flow you describe makes sense, and it gives us flexibility in case drive strategies need more control over `DriveTrainSubsystem`.
